In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('churn_clean.csv')

In [3]:
df.head()

,CaseOrder,Customer_id,Interaction,UID,City,State,County,Zip,Lat,Lng,...,MonthlyCharge,Bandwidth_GB_Year,Item1,Item2,Item3,Item4,Item5,Item6,Item7,Item8
0,1,K409198,aa90260b-4141-4a24-8e36-b04ce1f4f77b,e885b299883d4f9fb18e39c75155d990,Point Baker,AK,Prince of Wales-Hyder,99927,56.25100,-133.37571,...,172.455519,904.536110,5,5,5,3,4,4,3,4
1,2,S120509,fb76459f-c047-4a9d-8af9-e0f7d4ac2524,f2de8bef964785f41a2959829830fb8a,West Branch,MI,Ogemaw,48661,44.32893,-84.24080,...,242.632554,800.982766,3,4,3,3,4,3,4,4
2,3,K191035,344d114c-3736-4be5-98f7-c72c281e2d35,f1784cfa9f6d92ae816197eb175d3c71,Yamhill,OR,Yamhill,97148,45.35589,-123.24657,...,159.947583,2054.706961,4,4,2,4,4,3,3,3
3,4,D90850,abfa2b40-2d43-4994-b15a-989b8c79e311,dc8a365077241bb5cd5ccd305136b05e,Del Mar,CA,San Diego,92014,32.96687,-117.24798,...,119.956840,2164.579412,4,4,4,2,5,4,3,3
4,5,K662701,68a861fd-0d20-4e51-a587-8a90407ee574,aabb64a116e83fdc4befc1fbab1663f9,Needville,TX,Fort Bend,77461,29.38012,-95.80673,...,149.948316,271.493436,4,4,4,3,4,4,4,5

In [4]:
df_first = df.head(1).transpose()

In [5]:
df_first['a'] = df.dtypes

In [6]:
df_first.rename(columns={0: 'Example', 'a': 'DataType'}, inplace=True)

In [7]:
df_first.head()

                                          Example DataType
CaseOrder                                       1    int64
Customer_id                               K409198   object
Interaction  aa90260b-4141-4a24-8e36-b04ce1f4f77b   object
UID              e885b299883d4f9fb18e39c75155d990   object
City                                  Point Baker   object

In [8]:
df_first['DataCat'] = np.where(df_first['DataType'] == 'object','Qualitative', 'Quantitative' )

In [9]:
df_first.loc['Zip', 'DataCat'] = 'Qualitative'

In [10]:
df_first.loc['Item1':, 'DataCat'] = 'Qualitative'

In [11]:
df_first.index.names = ['Variable Name']

In [12]:
df_first.to_csv('variables.csv')

In [13]:
df_first['Explenation'] = ''

In [14]:
df_first

,Example,DataType,DataCat,Explenation
Variable Name,,,,
CaseOrder,1,int64,Quantitative,
Customer_id,K409198,object,Qualitative,
Interaction,aa90260b-4141-4a24-8e36-b04ce1f4f77b,object,Qualitative,
UID,e885b299883d4f9fb18e39c75155d990,object,Qualitative,
City,Point Baker,object,Qualitative,
State,AK,object,Qualitative,
County,Prince of Wales-Hyder,object,Qualitative,
Zip,99927,int64,Qualitative,
Lat,56.251,float64,Quantitative,
Lng,-133.37571,float64,Quantitative,
Population,38,int64,Quantitative,
Area,Urban,object,Qualitative,
TimeZone,America/Sitka,object,Qualitative,
Job,Environmental health practitioner,object,Qualitative,
Children,0,int64,Quantitative,
Age,68,int64,Quantitative,
Income,28561.99,float64,Quantitative,
Marital,Widowed,object,Qualitative,
Gender,Male,object,Qualitative,
Churn,No,object,Qualitative,
Outage_sec_perweek,7.978323,float64,Quantitative,
Email,10,int64,Quantitative,
Contacts,0,int64,Quantitative,
Yearly_equip_failure,1,int64,Quantitative,
Techie,No,object,Qualitative,
Contract,One year,object,Qualitative,
Port_modem,Yes,object,Qualitative,
Tablet,Yes,object,Qualitative,
InternetService,Fiber Optic,object,Qualitative,
Phone,Yes,object,Qualitative,
Multiple,No,object,Qualitative,
OnlineSecurity,Yes,object,Qualitative,
OnlineBackup,Yes,object,Qualitative,
DeviceProtection,No,object,Qualitative,
TechSupport,No,object,Qualitative,
StreamingTV,No,object,Qualitative,
StreamingMovies,Yes,object,Qualitative,
PaperlessBilling,Yes,object,Qualitative,
PaymentMethod,Credit Card (automatic),object,Qualitative,
Tenure,6.795513,float64,Quantitative,
MonthlyCharge,172.455519,float64,Quantitative,
Bandwidth_GB_Year,904.53611,float64,Quantitative,
Item1,5,int64,Qualitative,
Item2,5,int64,Qualitative,
Item3,5,int64,Qualitative,
Item4,3,int64,Qualitative,
Item5,4,int64,Qualitative,
Item6,4,int64,Qualitative,
Item7,3,int64,Qualitative,
Item8,4,int64,Qualitative,

In [15]:
df.columns

Index(['CaseOrder', 'Customer_id', 'Interaction', 'UID', 'City', 'State',
       'County', 'Zip', 'Lat', 'Lng', 'Population', 'Area', 'TimeZone', 'Job',
       'Children', 'Age', 'Income', 'Marital', 'Gender', 'Churn',
       'Outage_sec_perweek', 'Email', 'Contacts', 'Yearly_equip_failure',
       'Techie', 'Contract', 'Port_modem', 'Tablet', 'InternetService',
       'Phone', 'Multiple', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'PaperlessBilling', 'PaymentMethod', 'Tenure', 'MonthlyCharge',
       'Bandwidth_GB_Year', 'Item1', 'Item2', 'Item3', 'Item4', 'Item5',
       'Item6', 'Item7', 'Item8'],
      dtype='object', name='Variable Name')

In [63]:
df_first.iloc[0,3] = 'This column is a place holder to ensure the orignal order will be kept.'

In [64]:
df_first.iloc[1,3] = 'This column contains a unique ID for the customer.'

In [65]:
df_first.iloc[2,3] =  """A unique ID which relates to technical interactions,
                        including sign-up, support and transactions."""

In [66]:
df_first.iloc[3,3] = """A unique ID which relates to technical interactions,
                        including sign-up, support and transactions."""

In [67]:
df_first.iloc[4,3] = 'The city included on the billing address of the customer.'

In [68]:
df_first.iloc[5,3] = 'The state included on the billing address of the customer.'

In [69]:
df_first.iloc[6,3] = 'The county included on the billing address of the customer.'

In [70]:
df_first.iloc[7,3] = 'The zipcode included on the billing address of the customer.'

In [71]:
df_first.iloc[8,3] = 'The latitude based on the billing address of the customer.'

In [72]:
df_first.iloc[9,3] = 'The longitude based on the billing address of the customer.'

In [73]:
df_first.iloc[10,3] = 'The population within a one mile radius of the customer, retrieved from census data.'

In [74]:
df_first.iloc[11,3] = 'Categorized area type retrieved from census data. Can be one of the following: rural, urban and suburban.'

In [75]:
df_first.iloc[12,3] = 'Timezone of the customer based on sign-up info (not billing).'

In [76]:
df_first.iloc[13,3] = 'Profession of the customer, based on sign-up info.'

In [77]:
df_first.iloc[14,3] = 'Amount of children the customer has, based on sign-up info.'

In [78]:
df_first.iloc[15,3] = 'Age of the customer, based on sign-up info.'

In [79]:
df_first.iloc[16,3] = 'Annual income of the customer, based on sign-up info.'

In [80]:
df_first.iloc[17,3] = 'Marital Status of the customer, based on sign-up info.'

In [81]:
df_first.iloc[18,3] = 'Gender of the customer, based on sign-up info.'

In [82]:
df_first.iloc[19,3] = 'Whether the customer has churned or not. This is the target variable for future model predictions. Answer can be yes or no.'

In [83]:
df_first.iloc[20,3] = 'The average time in seconds the customer\'s neighberhood experienced system outages.'

In [84]:
df_first.iloc[21,3] = 'The amount of emails that were sent to customer in the previous year.'

In [85]:
df_first.iloc[22,3] = 'The amount of times the customer reached out to customer support. If they\'re a new customer, similar contacts in the new customer\'s profile.'

In [86]:
df_first.iloc[23,3] = 'How many times did the customer\'s equipment fail, and it was either replaced or reset. If they\'re a new customer, similar failures in the new customer\'s profile.'

In [87]:
df_first.iloc[24,3] = 'Does the customer consider themselves technically savy. This question was asked on the sign-up questionnaire. Answer can be yes or no.'

In [109]:
df_first.iloc[25,3] = 'How long is the customers contract for. Can be either monthly, annualy or for two years.'

In [110]:
df_first.iloc[26,3] = 'Does the customer have a portable modem or not. Answer can be yes or no.'

In [111]:
df_first.iloc[27,3] = 'Does the customer own a tablet or not. Answer can be yes or no.'

In [112]:
df_first.iloc[28,3] = 'The internet service provider of the customer.'

In [113]:
df_first.iloc[29,3] = 'Does the customer own a phone or not. Answer can be yes or no.'

In [114]:
df_first.iloc[30,3] = 'Does the customer have multiple phone lines or not. Answer can be yes or no.'

In [115]:
df_first.iloc[31,3] = 'Does the customer have the online security add-on or not. Answer can be yes or no.'

In [116]:
df_first.iloc[32,3] = 'Does the customer have the online backup add-on or not. Answer can be yes or no.'

In [117]:
df_first.iloc[33,3] = 'Does the customer have the device protection add-on or not. Answer can be yes or no.'

In [118]:
df_first.iloc[34,3] = 'Does the customer have the technical support add-on or not. Answer can be yes or no.'

In [119]:
df_first.iloc[35,3] = 'Does the customer have streaming TV or not. Answer can be yes or no.'

In [120]:
df_first.iloc[36,3] = 'Does the customer have streaming movies or not. Answer can be yes or no.'

In [121]:
df_first.iloc[37,3] = 'Does the customer have paperless billing or not. Answer can be yes or no.'

In [122]:
df_first

,Example,DataType,DataCat,Explenation
Variable Name,,,,
CaseOrder,1,int64,Quantitative,This column is a place holder to ensure the or...
Customer_id,K409198,object,Qualitative,This column contains a unique ID for the custo...
Interaction,aa90260b-4141-4a24-8e36-b04ce1f4f77b,object,Qualitative,A unique ID which relates to technical interac...
UID,e885b299883d4f9fb18e39c75155d990,object,Qualitative,A unique ID which relates to technical interac...
City,Point Baker,object,Qualitative,The city included on the billing address of th...
State,AK,object,Qualitative,The state included on the billing address of t...
County,Prince of Wales-Hyder,object,Qualitative,The county included on the billing address of ...
Zip,99927,int64,Qualitative,The zipcode included on the billing address of...
Lat,56.251,float64,Quantitative,The latitude based on the billing address of t...
Lng,-133.37571,float64,Quantitative,The longitude based on the billing address of ...
Population,38,int64,Quantitative,The population within a one mile radius of the...
Area,Urban,object,Qualitative,Categorized area type retrieved from census da...
TimeZone,America/Sitka,object,Qualitative,Timezone of the customer based on sign-up info...
Job,Environmental health practitioner,object,Qualitative,"Profession of the customer, based on sign-up i..."
Children,0,int64,Quantitative,"Amount of children the customer has, based on ..."
Age,68,int64,Quantitative,"Age of the customer, based on sign-up info."
Income,28561.99,float64,Quantitative,"Annual income of the customer, based on sign-u..."
Marital,Widowed,object,Qualitative,"Marital Status of the customer, based on sign-..."
Gender,Male,object,Qualitative,"Gender of the customer, based on sign-up info."
Churn,No,object,Qualitative,Whether the customer has churned or not. This ...
Outage_sec_perweek,7.978323,float64,Quantitative,The average time in seconds the customer's nei...
Email,10,int64,Quantitative,The amount of emails that were sent to custome...
Contacts,0,int64,Quantitative,The amount of times the customer reached out t...
Yearly_equip_failure,1,int64,Quantitative,How many times did the customer's equipment fa...
Techie,No,object,Qualitative,Does the customer consider themselves technica...
Contract,One year,object,Qualitative,How long is the customers contract for. Can be...
Port_modem,Yes,object,Qualitative,Does the customer have a portable modem or not...
Tablet,Yes,object,Qualitative,Does the customer own a tablet or not. Answer ...
InternetService,Fiber Optic,object,Qualitative,The internet service provider of the customer.
Phone,Yes,object,Qualitative,Does the customer own a phone or not. Answer c...
Multiple,No,object,Qualitative,Does the customer have multiple phone lines or...
OnlineSecurity,Yes,object,Qualitative,Does the customer have the online security add...
OnlineBackup,Yes,object,Qualitative,Does the customer have the online backup add-o...
DeviceProtection,No,object,Qualitative,Does the customer have the device protection a...
TechSupport,No,object,Qualitative,Does the customer have the technical support a...
StreamingTV,No,object,Qualitative,Does the customer have streaming TV or not. An...
StreamingMovies,Yes,object,Qualitative,Does the customer have streaming movies or not...
PaperlessBilling,Yes,object,Qualitative,Does the customer have paperless billing or no...
PaymentMethod,Credit Card (automatic),object,Qualitative,
Tenure,6.795513,float64,Quantitative,
MonthlyCharge,172.455519,float64,Quantitative,
Bandwidth_GB_Year,904.53611,float64,Quantitative,
Item1,5,int64,Qualitative,
Item2,5,int64,Qualitative,
Item3,5,int64,Qualitative,
Item4,3,int64,Qualitative,
Item5,4,int64,Qualitative,
Item6,4,int64,Qualitative,
Item7,3,int64,Qualitative,
Item8,4,int64,Qualitative,