In [446]:
import pandas as pd
import numpy as np

In [447]:
df = pd.read_csv('churn_clean.csv')

In [448]:
df.head()

,CaseOrder,Customer_id,Interaction,UID,City,State,County,Zip,Lat,Lng,...,MonthlyCharge,Bandwidth_GB_Year,Item1,Item2,Item3,Item4,Item5,Item6,Item7,Item8
0,1,K409198,aa90260b-4141-4a24-8e36-b04ce1f4f77b,e885b299883d4f9fb18e39c75155d990,Point Baker,AK,Prince of Wales-Hyder,99927,56.25100,-133.37571,...,172.455519,904.536110,5,5,5,3,4,4,3,4
1,2,S120509,fb76459f-c047-4a9d-8af9-e0f7d4ac2524,f2de8bef964785f41a2959829830fb8a,West Branch,MI,Ogemaw,48661,44.32893,-84.24080,...,242.632554,800.982766,3,4,3,3,4,3,4,4
2,3,K191035,344d114c-3736-4be5-98f7-c72c281e2d35,f1784cfa9f6d92ae816197eb175d3c71,Yamhill,OR,Yamhill,97148,45.35589,-123.24657,...,159.947583,2054.706961,4,4,2,4,4,3,3,3
3,4,D90850,abfa2b40-2d43-4994-b15a-989b8c79e311,dc8a365077241bb5cd5ccd305136b05e,Del Mar,CA,San Diego,92014,32.96687,-117.24798,...,119.956840,2164.579412,4,4,4,2,5,4,3,3
4,5,K662701,68a861fd-0d20-4e51-a587-8a90407ee574,aabb64a116e83fdc4befc1fbab1663f9,Needville,TX,Fort Bend,77461,29.38012,-95.80673,...,149.948316,271.493436,4,4,4,3,4,4,4,5

In [449]:
df_first = df.head(1).transpose()

In [450]:
df_first['a'] = df.dtypes

In [451]:
df_first.rename(columns={0: 'Example', 'a': 'DataType'}, inplace=True)

In [452]:
df_first.head()

                                          Example DataType
CaseOrder                                       1    int64
Customer_id                               K409198   object
Interaction  aa90260b-4141-4a24-8e36-b04ce1f4f77b   object
UID              e885b299883d4f9fb18e39c75155d990   object
City                                  Point Baker   object

In [453]:
df_first['DataCat'] = np.where(df_first['DataType'] == 'object','Qualitative', 'Quantitative' )

In [454]:
df_first.loc['Zip', 'DataCat'] = 'Qualitative'

In [455]:
df_first.loc['Item1':, 'DataCat'] = 'Qualitative'

In [456]:
df_first.index.names = ['Variable Name']

In [457]:
df_first.to_csv('variables.csv')

In [458]:
df_first['Explanation'] = ''

In [459]:
df_first

,Example,DataType,DataCat,Explanation
Variable Name,,,,
CaseOrder,1,int64,Quantitative,
Customer_id,K409198,object,Qualitative,
Interaction,aa90260b-4141-4a24-8e36-b04ce1f4f77b,object,Qualitative,
UID,e885b299883d4f9fb18e39c75155d990,object,Qualitative,
City,Point Baker,object,Qualitative,
State,AK,object,Qualitative,
County,Prince of Wales-Hyder,object,Qualitative,
Zip,99927,int64,Qualitative,
Lat,56.251,float64,Quantitative,
Lng,-133.37571,float64,Quantitative,
Population,38,int64,Quantitative,
Area,Urban,object,Qualitative,
TimeZone,America/Sitka,object,Qualitative,
Job,Environmental health practitioner,object,Qualitative,
Children,0,int64,Quantitative,
Age,68,int64,Quantitative,
Income,28561.99,float64,Quantitative,
Marital,Widowed,object,Qualitative,
Gender,Male,object,Qualitative,
Churn,No,object,Qualitative,
Outage_sec_perweek,7.978323,float64,Quantitative,
Email,10,int64,Quantitative,
Contacts,0,int64,Quantitative,
Yearly_equip_failure,1,int64,Quantitative,
Techie,No,object,Qualitative,
Contract,One year,object,Qualitative,
Port_modem,Yes,object,Qualitative,
Tablet,Yes,object,Qualitative,
InternetService,Fiber Optic,object,Qualitative,
Phone,Yes,object,Qualitative,
Multiple,No,object,Qualitative,
OnlineSecurity,Yes,object,Qualitative,
OnlineBackup,Yes,object,Qualitative,
DeviceProtection,No,object,Qualitative,
TechSupport,No,object,Qualitative,
StreamingTV,No,object,Qualitative,
StreamingMovies,Yes,object,Qualitative,
PaperlessBilling,Yes,object,Qualitative,
PaymentMethod,Credit Card (automatic),object,Qualitative,
Tenure,6.795513,float64,Quantitative,
MonthlyCharge,172.455519,float64,Quantitative,
Bandwidth_GB_Year,904.53611,float64,Quantitative,
Item1,5,int64,Qualitative,
Item2,5,int64,Qualitative,
Item3,5,int64,Qualitative,
Item4,3,int64,Qualitative,
Item5,4,int64,Qualitative,
Item6,4,int64,Qualitative,
Item7,3,int64,Qualitative,
Item8,4,int64,Qualitative,

In [460]:
df.columns

Index(['CaseOrder', 'Customer_id', 'Interaction', 'UID', 'City', 'State',
       'County', 'Zip', 'Lat', 'Lng', 'Population', 'Area', 'TimeZone', 'Job',
       'Children', 'Age', 'Income', 'Marital', 'Gender', 'Churn',
       'Outage_sec_perweek', 'Email', 'Contacts', 'Yearly_equip_failure',
       'Techie', 'Contract', 'Port_modem', 'Tablet', 'InternetService',
       'Phone', 'Multiple', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'PaperlessBilling', 'PaymentMethod', 'Tenure', 'MonthlyCharge',
       'Bandwidth_GB_Year', 'Item1', 'Item2', 'Item3', 'Item4', 'Item5',
       'Item6', 'Item7', 'Item8'],
      dtype='object', name='Variable Name')

In [524]:
df_first.iloc[0,3] = 'This column is a place holder to ensure the original order will be kept.'

In [462]:
df_first.iloc[1,3] = 'This column contains a unique ID for the customer.'

In [463]:
df_first.iloc[2,3] =  """A unique ID which relates to technical interactions,
                        including sign-up, support and transactions."""

In [464]:
df_first.iloc[3,3] = """A unique ID which relates to technical interactions,
                        including sign-up, support and transactions."""

In [465]:
df_first.iloc[4,3] = 'The city included on the billing address of the customer.'

In [466]:
df_first.iloc[5,3] = 'The state included on the billing address of the customer.'

In [467]:
df_first.iloc[6,3] = 'The county included on the billing address of the customer.'

In [468]:
df_first.iloc[7,3] = 'The zipcode included on the billing address of the customer.'

In [469]:
df_first.iloc[8,3] = 'The latitude based on the billing address of the customer.'

In [470]:
df_first.iloc[9,3] = 'The longitude based on the billing address of the customer.'

In [471]:
df_first.iloc[10,3] = 'The population within a one mile radius of the customer, retrieved from census data.'

In [472]:
df_first.iloc[11,3] = 'Categorized area type retrieved from census data. Can be one of the following: rural, urban and suburban.'

In [473]:
df_first.iloc[12,3] = 'Timezone of the customer based on sign-up info (not billing).'

In [474]:
df_first.iloc[13,3] = 'Profession of the customer, based on sign-up info.'

In [475]:
df_first.iloc[14,3] = 'Amount of children the customer has, based on sign-up info.'

In [476]:
df_first.iloc[15,3] = 'Age of the customer, based on sign-up info.'

In [477]:
df_first.iloc[16,3] = 'Annual income of the customer, based on sign-up info.'

In [478]:
df_first.iloc[17,3] = 'Marital Status of the customer, based on sign-up info.'

In [479]:
df_first.iloc[18,3] = 'Gender of the customer, based on sign-up info.'

In [480]:
df_first.iloc[19,3] = 'Whether the customer has churned or not. This is the target variable for future model predictions. Answer can be yes or no.'

In [481]:
df_first.iloc[20,3] = 'The average time in seconds the customer\'s neighberhood experienced system outages.'

In [482]:
df_first.iloc[21,3] = 'The amount of emails that were sent to customer in the previous year.'

In [483]:
df_first.iloc[22,3] = 'The amount of times the customer reached out to customer support. For new customers, this column reflects the amount of times customers with simillar profiles have reached out to customer support.'

In [484]:
df_first.iloc[23,3] = 'How many times did the customer\'s equipment fail durng the previous year, and it was either replaced or reset. For new customers, this column reflects the amount of times customers with simillar profiles have experienced equipment failures.'

In [485]:
df_first.iloc[24,3] = 'Does the customer consider themselves technically savy. This question was asked on the sign-up questionnaire. Answer can be yes or no.'

In [486]:
df_first.iloc[25,3] = 'How long is the customer\'s contract for. Can be either monthly, annualy or for two years.'

In [487]:
df_first.iloc[26,3] = 'Does the customer have a portable modem or not. Answer can be yes or no.'

In [488]:
df_first.iloc[27,3] = 'Does the customer own a tablet or not. Answer can be yes or no.'

In [489]:
df_first.iloc[28,3] = 'The internet service provider of the customer.'

In [490]:
df_first.iloc[29,3] = 'Does the customer own a phone or not. Answer can be yes or no.'

In [491]:
df_first.iloc[30,3] = 'Does the customer have multiple phone lines or not. Answer can be yes or no.'

In [492]:
df_first.iloc[31,3] = 'Does the customer have the online security add-on or not. Answer can be yes or no.'

In [493]:
df_first.iloc[32,3] = 'Does the customer have the online backup add-on or not. Answer can be yes or no.'

In [494]:
df_first.iloc[33,3] = 'Does the customer have the device protection add-on or not. Answer can be yes or no.'

In [495]:
df_first.iloc[34,3] = 'Does the customer have the technical support add-on or not. Answer can be yes or no.'

In [496]:
df_first.iloc[35,3] = 'Does the customer have streaming TV or not. Answer can be yes or no.'

In [497]:
df_first.iloc[36,3] = 'Does the customer have streaming movies or not. Answer can be yes or no.'

In [498]:
df_first.iloc[37,3] = 'Does the customer have paperless billing or not. Answer can be yes or no.'

In [499]:
df_first.iloc[38,3] = 'How does the customer pay for the service. Answer can be: check (mailed, electronic), or automatic (bank trasfer, credit card).'

In [500]:
df_first.iloc[39,3] = 'The amount of time in months the customer has retained service.'

In [501]:
df_first.iloc[40,3] = 'How much does the customer pay per month on average. For new customers, this column reflects the average spend value for customers with the same profile.'

In [502]:
df_first.iloc[41,3] = 'How many GB of data does the customer use per year on average. For new customers who haven\'t yet concluded a year of service, this column reflects the either the data usage approximated from thier use up to this point, or average data usage for regular customers within the same demographic profile.'

In [535]:
df_first['Variable'] = df_first.index

In [536]:
df_export = df_first[['Variable','DataCat','Explanation', 'Example']]

In [537]:
df_export['DataCat'] = '\n\u2022 Data Type: ' + df_first['DataCat']
df_export.Explanation  = '\n\u2022 ' + df_export.Explanation
df_export.Example  = '\n\u2022 Example: ' + df_export.Example.astype(str)

/var/folders/kp/qpd_hfrx4rsf69s67ws3jxkr0000gn/T/ipykernel_16062/4143171363.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_export['DataCat'] = '\n\u2022 Data Type: ' + df_first['DataCat']
/var/folders/kp/qpd_hfrx4rsf69s67ws3jxkr0000gn/T/ipykernel_16062/4143171363.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_export.Explanation  = '\n\u2022 ' + df_export.Explanation
/var/folders/kp/qpd_hfrx4rsf69s67ws3jxkr0000gn/T/ipykernel_16062/4143171363.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_export.Example  = '\n\u2022 Example: ' + df_export.Example.astype(str)

In [538]:
df_export

,Variable,DataCat,Explanation,Example
Variable Name,,,,
CaseOrder,CaseOrder,\nâ€¢ Data Type: Quantitative,\nâ€¢ This column is a place holder to ensure th...,\nâ€¢ Example: 1
Customer_id,Customer_id,\nâ€¢ Data Type: Qualitative,\nâ€¢ This column contains a unique ID for the c...,\nâ€¢ Example: K409198
Interaction,Interaction,\nâ€¢ Data Type: Qualitative,\nâ€¢ A unique ID which relates to technical int...,\nâ€¢ Example: aa90260b-4141-4a24-8e36-b04ce1f4f77b
UID,UID,\nâ€¢ Data Type: Qualitative,\nâ€¢ A unique ID which relates to technical int...,\nâ€¢ Example: e885b299883d4f9fb18e39c75155d990
City,City,\nâ€¢ Data Type: Qualitative,\nâ€¢ The city included on the billing address o...,\nâ€¢ Example: Point Baker
State,State,\nâ€¢ Data Type: Qualitative,\nâ€¢ The state included on the billing address ...,\nâ€¢ Example: AK
County,County,\nâ€¢ Data Type: Qualitative,\nâ€¢ The county included on the billing address...,\nâ€¢ Example: Prince of Wales-Hyder
Zip,Zip,\nâ€¢ Data Type: Qualitative,\nâ€¢ The zipcode included on the billing addres...,\nâ€¢ Example: 99927
Lat,Lat,\nâ€¢ Data Type: Quantitative,\nâ€¢ The latitude based on the billing address ...,\nâ€¢ Example: 56.251
Lng,Lng,\nâ€¢ Data Type: Quantitative,\nâ€¢ The longitude based on the billing address...,\nâ€¢ Example: -133.37571
Population,Population,\nâ€¢ Data Type: Quantitative,\nâ€¢ The population within a one mile radius of...,\nâ€¢ Example: 38
Area,Area,\nâ€¢ Data Type: Qualitative,\nâ€¢ Categorized area type retrieved from censu...,\nâ€¢ Example: Urban
TimeZone,TimeZone,\nâ€¢ Data Type: Qualitative,\nâ€¢ Timezone of the customer based on sign-up ...,\nâ€¢ Example: America/Sitka
Job,Job,\nâ€¢ Data Type: Qualitative,"\nâ€¢ Profession of the customer, based on sign-...",\nâ€¢ Example: Environmental health practitioner
Children,Children,\nâ€¢ Data Type: Quantitative,"\nâ€¢ Amount of children the customer has, based...",\nâ€¢ Example: 0
Age,Age,\nâ€¢ Data Type: Quantitative,"\nâ€¢ Age of the customer, based on sign-up info.",\nâ€¢ Example: 68
Income,Income,\nâ€¢ Data Type: Quantitative,"\nâ€¢ Annual income of the customer, based on si...",\nâ€¢ Example: 28561.99
Marital,Marital,\nâ€¢ Data Type: Qualitative,"\nâ€¢ Marital Status of the customer, based on s...",\nâ€¢ Example: Widowed
Gender,Gender,\nâ€¢ Data Type: Qualitative,"\nâ€¢ Gender of the customer, based on sign-up i...",\nâ€¢ Example: Male
Churn,Churn,\nâ€¢ Data Type: Qualitative,\nâ€¢ Whether the customer has churned or not. T...,\nâ€¢ Example: No
Outage_sec_perweek,Outage_sec_perweek,\nâ€¢ Data Type: Quantitative,\nâ€¢ The average time in seconds the customer's...,\nâ€¢ Example: 7.978322947
Email,Email,\nâ€¢ Data Type: Quantitative,\nâ€¢ The amount of emails that were sent to cus...,\nâ€¢ Example: 10
Contacts,Contacts,\nâ€¢ Data Type: Quantitative,\nâ€¢ The amount of times the customer reached o...,\nâ€¢ Example: 0
Yearly_equip_failure,Yearly_equip_failure,\nâ€¢ Data Type: Quantitative,\nâ€¢ How many times did the customer's equipmen...,\nâ€¢ Example: 1
Techie,Techie,\nâ€¢ Data Type: Qualitative,\nâ€¢ Does the customer consider themselves tech...,\nâ€¢ Example: No
Contract,Contract,\nâ€¢ Data Type: Qualitative,\nâ€¢ How long is the customer's contract for. C...,\nâ€¢ Example: One year
Port_modem,Port_modem,\nâ€¢ Data Type: Qualitative,\nâ€¢ Does the customer have a portable modem or...,\nâ€¢ Example: Yes
Tablet,Tablet,\nâ€¢ Data Type: Qualitative,\nâ€¢ Does the customer own a tablet or not. Ans...,\nâ€¢ Example: Yes
InternetService,InternetService,\nâ€¢ Data Type: Qualitative,\nâ€¢ The internet service provider of the custo...,\nâ€¢ Example: Fiber Optic
Phone,Phone,\nâ€¢ Data Type: Qualitative,\nâ€¢ Does the customer own a phone or not. Answ...,\nâ€¢ Example: Yes
Multiple,Multiple,\nâ€¢ Data Type: Qualitative,\nâ€¢ Does the customer have multiple phone line...,\nâ€¢ Example: No
OnlineSecurity,OnlineSecurity,\nâ€¢ Data Type: Qualitative,\nâ€¢ Does the customer have the online security...,\nâ€¢ Example: Yes
OnlineBackup,OnlineBackup,\nâ€¢ Data Type: Qualitative,\nâ€¢ Does the customer have the online backup a...,\nâ€¢ Example: Yes
DeviceProtection,DeviceProtection,\nâ€¢ Data Type: Qualitative,\nâ€¢ Does the customer have the device protecti...,\nâ€¢ Example: No
TechSupport,TechSupport,\nâ€¢ Data Type: Qualitative,\nâ€¢ Does the customer have the technical suppo...,\nâ€¢ Example: No
StreamingTV,StreamingTV,\nâ€¢ Data Type: Qualitative,\nâ€¢ Does the customer have streaming TV or not...,\nâ€¢ Example: No
StreamingMovies,StreamingMovies,\nâ€¢ Data Type: Qualitative,\nâ€¢ Does the customer have streaming movies or...,\nâ€¢ Example: Yes
PaperlessBilling,PaperlessBilling,\nâ€¢ Data Type: Qualitative,\nâ€¢ Does the customer have paperless billing o...,\nâ€¢ Example: Yes
PaymentMethod,PaymentMethod,\nâ€¢ Data Type: Qualitative,\nâ€¢ How does the customer pay for the service....,\nâ€¢ Example: Credit Card (automatic)
Tenure,Tenure,\nâ€¢ Data Type: Quantitative,\nâ€¢ The amount of time in months the customer ...,\nâ€¢ Example: 6.795512947
MonthlyCharge,MonthlyCharge,\nâ€¢ Data Type: Quantitative,\nâ€¢ How much does the customer pay per month o...,\nâ€¢ Example: 172.455519
Bandwidth_GB_Year,Bandwidth_GB_Year,\nâ€¢ Data Type: Quantitative,\nâ€¢ How many GB of data does the customer use ...,\nâ€¢ Example: 904.5361102
Item1,Item1,\nâ€¢ Data Type: Qualitative,\nâ€¢,\nâ€¢ Example: 5
Item2,Item2,\nâ€¢ Data Type: Qualitative,\nâ€¢,\nâ€¢ Example: 5
Item3,Item3,\nâ€¢ Data Type: Qualitative,\nâ€¢,\nâ€¢ Example: 5
Item4,Item4,\nâ€¢ Data Type: Qualitative,\nâ€¢,\nâ€¢ Example: 3
Item5,Item5,\nâ€¢ Data Type: Qualitative,\nâ€¢,\nâ€¢ Example: 4
Item6,Item6,\nâ€¢ Data Type: Qualitative,\nâ€¢,\nâ€¢ Example: 4
Item7,Item7,\nâ€¢ Data Type: Qualitative,\nâ€¢,\nâ€¢ Example: 3
Item8,Item8,\nâ€¢ Data Type: Qualitative,\nâ€¢,\nâ€¢ Example: 4

In [539]:
np.savetxt('b.txt', df_export, newline='\n\n',  fmt = "%s")